### ISSUE TITLE
install_dir needs parent directory

### ISSUE THREAD

**Issue by klyonrad** [JonathanTron/chef-sentry#14]
This is a minor annoyance:

When another directory is used, chef run fails without a parent directory

```ruby
directory node["sentry"]["install_dir"] do
  owner sentry_user
  group sentry_group
end
```

a simple `recursive true` would be nice

**Comment by nilroy** [comment]
@klyonrad https://github.com/JonathanTron/chef-sentry/pull/15 takes care of this
