### ISSUE TITLE
sentry loaddata is not there in sentry 8.1.2

### ISSUE THREAD

**Issue by nilroy** [JonathanTron/chef-sentry#5]
@JonathanTron 
sentry loaddata is not present in sentry 8.1.2. I shall create a PR to fix this. Let me know if you are already working on this.

**Comment by nilroy** [comment]
The sentry community answer: https://github.com/getsentry/sentry/issues/2683

**Comment by JonathanTron** [comment]
Hi @nilroy, thanks for reporting it. 

I'm not currently working on it, it would be amazing if you could work on a PR for this.

**Comment by nilroy** [comment]
@JonathanTron No issue. I shall work on it

**Comment by nilroy** [comment]
@JonathanTron I think something has changed recently with sentry. Even in version 7.4.3 I am not able to run the sentry upgrade. It gives following error
`STDERR: FATAL ERROR - The following SQL query failed: ALTER TABLE "sentry_authprovider" ALTER COLUMN "config" TYPE jsonb, ALTER COLUMN "config" DROP NOT NULL, ALTER COLUMN "config" DROP DEFAULT;
The error was: column "config" cannot be cast automatically to type jsonb
HINT:  You might need to specify "USING config::jsonb".`
Any idea?

**Comment by nilroy** [comment]
@JonathanTron It seems sentry version prior to 7.7.x is having this issue. I think we should bump the version to 7.7.x by default. I shall do that in the same PR.

**Comment by nilroy** [comment]
@JonathanTron the PR https://github.com/JonathanTron/chef-sentry/pull/7 takes care of everything mentioned in this issue.
